import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Lightbulb, Volume2 } from 'lucide-react';
import { SUBTRACTION_CHAPTERS, createSubtractionRun, createArithmeticSeed, arithmeticRewardUnits } from '../../data/arithmeticAdventure.js';
import { getArithmeticProgress, saveArithmeticRun } from '../../data/arithmeticProgress.js';
import { SoundToggle } from '../shared/index.jsx';

const tell = (speak, text) => speak?.(text, { premium: false, segments: [text] });
const colorClass = { red: 'bg-rose-500', blue: 'bg-sky-500', gold: 'bg-amber-400', pink: 'bg-pink-400', violet: 'bg-violet-500', brown: 'bg-amber-800', teal: 'bg-teal-500' };
const group = (n, color, label, removed = 0) => <div role="group" aria-label={`${label}, ${n} counters${removed ? `, ${removed} crossed out` : ''}`} className="min-w-24 rounded-2xl border-2 border-slate-200 bg-white p-2"><p className="text-xs font-black text-slate-700">{label}: {n}</p><div className="mt-1 flex max-w-56 flex-wrap gap-1" aria-hidden="true">{Array.from({ length: n }, (_, i) => <span key={i} className={`relative h-5 w-5 rounded-full border-2 border-white shadow ${colorClass[color] || colorClass.teal} ${i < removed ? 'opacity-45' : ''}`}>{i < removed && <span className="absolute -top-2 left-0 text-xl font-black text-rose-700">×</span>}</span>)}</div></div>;
const Chapter = ({ chapter, index, selected, done, locked, onClick }) => <button type="button" disabled={locked} onClick={onClick} aria-pressed={selected} className={`min-h-16 rounded-2xl border-2 p-3 text-left font-black disabled:opacity-50 ${selected ? 'border-violet-600 bg-violet-100' : 'border-white bg-white'}`}><span className="block text-xs uppercase tracking-wide">Chapter {index + 1}{done ? ' · Badge earned' : locked ? ' · Locked' : ''}</span>{chapter.title}</button>;

export default function SubtractionStation({ onBack, playSfx = () => {}, soundOn, onToggleSound, speak = () => {}, onCelebrate = () => {}, onGameEvent, onPhaseChange, playerId = 'amari' }) {
  const [progress, setProgress] = useState(() => getArithmeticProgress('subtraction', playerId));
  const [chapterIndex, setChapterIndex] = useState(() => getArithmeticProgress('subtraction', playerId).unlockedChapter);
  const [phase, setPhase] = useState('start'); const [seed, setSeed] = useState(null); const [rounds, setRounds] = useState([]); const [roundIndex, setRoundIndex] = useState(0);
  const [mistake, setMistake] = useState(false); const [hintUsed, setHintUsed] = useState(false); const [locked, setLocked] = useState(false); const [feedback, setFeedback] = useState(''); const [firstCount, setFirstCount] = useState(0); const [motion, setMotion] = useState(false);
  const chapter = SUBTRACTION_CHAPTERS[chapterIndex]; const question = rounds[roundIndex];
  useEffect(() => { onPhaseChange?.(phase === 'done' ? 'finish' : phase === 'start' ? 'intro' : 'play'); }, [phase, onPhaseChange]);
  useEffect(() => { if (phase === 'play' && question) { onGameEvent?.('subtraction', 'question', { level: chapterIndex, round: roundIndex, seed, difficulty: chapter.id }); tell(speak, question.prompt); } }, [phase, question, chapterIndex, chapter.id, roundIndex, seed, speak, onGameEvent]);
  const start = (i = chapterIndex) => { const newSeed = createArithmeticSeed(); const recent = getArithmeticProgress('subtraction', playerId).recentQuestionIds[i] || []; const queue = createSubtractionRun({ chapter: i, seed: newSeed, recentIds: recent }); setChapterIndex(i); setSeed(newSeed); setRounds(queue); setRoundIndex(0); setMistake(false); setHintUsed(false); setLocked(false); setFeedback(''); setFirstCount(0); setMotion(false); setPhase('play'); onGameEvent?.('subtraction', 'start', { level: i, seed: newSeed, difficulty: SUBTRACTION_CHAPTERS[i].id }); };
  const attempt = (value) => { if (!question || locked) return; onGameEvent?.('subtraction', 'answer_attempt', { level: chapterIndex, round: roundIndex, seed, difficulty: chapter.id, firstAttempt: !mistake && !hintUsed }); if (value !== question.answer) { setMistake(true); setFeedback(question.type === 'compare' ? 'Pair one counter from each group. Count what is left unpaired.' : 'Look at the crossed objects. Count the ones that remain.'); playSfx('wrong'); return; }
    setLocked(true); setFeedback(question.explanation); setMotion(true); setFirstCount(n => n + (!mistake && !hintUsed ? 1 : 0)); playSfx('success'); onGameEvent?.('subtraction', 'answer_correct', { level: chapterIndex, round: roundIndex, seed, difficulty: chapter.id, skill: chapter.skill, item: question.id, response: value, expected: question.answer, correct: true, firstAttempt: !mistake && !hintUsed, hints: hintUsed ? 1 : 0 }); tell(speak, question.explanation);
  };
  const hint = () => { if (!question || locked || hintUsed) return; setHintUsed(true); setFeedback(question.clue); onGameEvent?.('subtraction', 'hint', { level: chapterIndex, round: roundIndex, seed, difficulty: chapter.id, hintType: 'one_step' }); tell(speak, question.clue); };
  const next = () => { if (!locked) return; if (roundIndex < 5) { setRoundIndex(n => n + 1); setMistake(false); setHintUsed(false); setLocked(false); setFeedback(''); setMotion(false); return; } const independent = firstCount + (!mistake && !hintUsed ? 1 : 0); const stars = independent >= 5 ? 3 : independent >= 3 ? 2 : 1; const result = saveArithmeticRun('subtraction', playerId, chapterIndex, rounds, stars); if (!result) return; setProgress(result.progress); if (result.awardedStars > 0) onCelebrate?.(`${chapter.title} complete!`, arithmeticRewardUnits(result.awardedStars), 0, 'math'); onGameEvent?.('subtraction', 'level_complete', { level: chapterIndex, round: 5, seed, difficulty: chapter.id }); setFeedback(`Chapter complete! You earned ${stars} ${stars === 1 ? 'star' : 'stars'}.`); setPhase('done'); playSfx('complete'); };
  const leave = () => { if (phase === 'play') onGameEvent?.('subtraction', 'leave', { level: chapterIndex, round: roundIndex, seed, difficulty: chapter.id }); onBack?.(); };
  const model = useMemo(() => { if (!question) return null; if (question.type === 'compare') return <div className="mx-auto max-w-sm rounded-2xl border-2 border-violet-200 bg-white p-3"><p className="mb-2 text-sm font-black">Pair matching counters. An unpaired counter is marked with a ring.</p><div role="group" aria-label={`Paired groups: Group A has ${question.a}, Group B has ${question.b}`} className="grid grid-cols-2 gap-x-3 gap-y-1">{Array.from({length:Math.max(question.a,question.b)},(_,i)=><div key={i} className="col-span-2 grid grid-cols-2 gap-3"><div className={`flex min-h-9 items-center justify-center rounded-lg ${i<question.a?'bg-sky-50':''}`}>{i<question.a&&<span className={`h-6 w-6 rounded-full ${colorClass.blue} ${i>=Math.min(question.a,question.b)?'ring-4 ring-amber-300':''}`} aria-label={`Group A counter ${i+1}${i>=Math.min(question.a,question.b)?', unpaired':''}`} />}</div><div className={`flex min-h-9 items-center justify-center rounded-lg ${i<question.b?'bg-amber-50':''}`}>{i<question.b&&<span className={`h-6 w-6 rounded-full ${colorClass.gold} ${i>=Math.min(question.a,question.b)?'ring-4 ring-amber-300':''}`} aria-label={`Group B counter ${i+1}${i>=Math.min(question.a,question.b)?', unpaired':''}`} />}</div></div>)}</div><div className="mt-2 flex justify-around text-sm font-black"><span>Group A: {question.a}</span><span>Group B: {question.b}</span></div><div className="mt-2 rounded-xl bg-violet-50 p-2 text-sm font-bold">Unpaired difference: {locked ? question.answer : '?'}</div></div>; return <div className={`flex flex-wrap items-center justify-center gap-3 ${motion ? 'animate-pulse' : ''}`}>{group(question.a, question.color, 'Starting group', locked ? question.b : 0)}<span aria-hidden="true" className="text-2xl font-black">−</span>{group(question.b, 'rose', question.type === 'story' ? 'Given away' : 'Take away') }<span aria-hidden="true" className="text-2xl">→</span><div role="group" aria-label={locked ? `Remaining tray, ${question.answer} counters` : 'Empty remaining tray'} className="min-w-24 rounded-2xl border-2 border-dashed border-violet-500 bg-violet-50 p-3"><b>Remaining</b><div className="mt-1 flex max-w-56 flex-wrap gap-1" aria-hidden="true">{locked&&Array.from({length:question.answer},(_,i)=><span key={i} className={`h-5 w-5 rounded-full ${colorClass[question.color]||colorClass.teal}`}/>)}</div></div></div>; }, [question, locked, motion]);
  if (phase === 'start' || phase === 'done') return <div className="min-h-[100dvh] bg-gradient-to-b from-violet-100 to-purple-200 p-3 text-slate-900 sm:p-6"><header className="mx-auto flex max-w-4xl items-center justify-between rounded-3xl bg-white p-3 shadow"><button className="game-icon-button !min-h-12 !min-w-12" onClick={leave} aria-label="Back to Maths Missions"><ArrowLeft /></button><h1 className="text-xl font-black sm:text-3xl">Subtraction Station</h1><SoundToggle soundOn={soundOn} onToggle={onToggleSound} /></header>{phase === 'start' ? <main className="mx-auto mt-5 max-w-4xl"><p className="mb-4 rounded-2xl bg-white p-4 text-center font-bold">Take away, compare groups, and solve stories. Each chapter has six questions and a worked answer you control.</p><div className="grid gap-3 sm:grid-cols-3">{SUBTRACTION_CHAPTERS.map((c,i)=><Chapter key={c.id} chapter={c} index={i} selected={chapterIndex===i} done={progress.completedChapterIds.includes(c.id)} locked={i>progress.unlockedChapter} onClick={()=>setChapterIndex(i)} />)}</div><button onClick={()=>start()} className="mt-5 min-h-14 w-full rounded-2xl bg-violet-700 px-5 text-lg font-black text-white">Start {chapter.title}</button></main> : <main className="mx-auto mt-8 max-w-2xl rounded-3xl bg-white p-6 text-center shadow-xl"><p className="text-2xl font-black">{feedback}</p><p className="mt-3">Choose the next unlocked chapter or replay a completed chapter.</p><button className="mt-5 min-h-14 w-full rounded-2xl bg-violet-700 px-5 font-black text-white" onClick={()=>{setPhase('start');setChapterIndex(progress.unlockedChapter);}}>Continue</button><button className="mt-3 min-h-14 w-full rounded-2xl bg-white px-5 font-black text-violet-800 ring-2 ring-violet-700" onClick={()=>start(chapterIndex)}>Replay {chapter.title}</button></main>}</div>;
  return <div className="min-h-[100dvh] overflow-y-auto bg-gradient-to-b from-violet-100 to-purple-200 p-3 text-slate-900 sm:p-6"><header className="mx-auto flex max-w-4xl items-center justify-between rounded-3xl bg-white p-3 shadow"><button className="game-icon-button !min-h-12 !min-w-12" onClick={leave} aria-label="Back to Maths Missions"><ArrowLeft /></button><div className="text-center"><p className="text-xs font-black uppercase">Chapter {chapterIndex+1} of 3 · Question {roundIndex+1} of 6</p><h1 className="text-xl font-black sm:text-3xl">Subtraction Station</h1></div><SoundToggle soundOn={soundOn} onToggle={onToggleSound} /></header><main className="mx-auto mt-4 max-w-4xl rounded-3xl bg-white/90 p-4 text-center shadow-xl sm:p-6"><p className="mb-3 text-lg font-bold" aria-live="polite">{question?.prompt}</p><button className="mb-4 inline-flex min-h-12 items-center gap-2 rounded-xl bg-violet-100 px-4 font-black" onClick={()=>tell(speak, question.prompt)}><Volume2 size={20}/> Hear question</button>{model}<div className="my-4 flex flex-wrap justify-center gap-3" role="group" aria-label="Choose the answer">{question?.options.map(option=><button key={option} disabled={locked} onClick={()=>attempt(option)} className="min-h-14 min-w-16 rounded-2xl bg-violet-700 px-5 text-2xl font-black text-white shadow disabled:opacity-60" aria-label={`Answer ${option}`}>{option}</button>)}</div>{feedback&&<p role="status" className="mx-auto mb-3 max-w-2xl rounded-xl bg-violet-50 p-3 font-bold">{feedback}</p>}{!locked&&<button disabled={hintUsed} onClick={hint} className="inline-flex min-h-12 items-center gap-2 rounded-xl border-2 border-amber-500 bg-amber-50 px-4 font-black disabled:opacity-50"><Lightbulb size={20}/>{hintUsed?'Hint used':'Use one hint'}</button>}{locked&&<button onClick={next} className="mt-3 min-h-14 w-full rounded-2xl bg-violet-700 px-5 text-lg font-black text-white">{roundIndex===5?'Finish chapter':'Next question'}</button>}</main></div>;
}
